packages:
  - 'packages/*'
  - 'playground'

catalog:
  '@types/node': ^20.0.0
  '@vue/test-utils': ^2.4.0
  '@vitejs/plugin-vue': ^6.0.0
  '@modelcontextprotocol/sdk': ^1.17.3
  jsdom: ^24.0.0
  typescript: ^5.9.2
  vite: ^7.1.3
  vitest: ^1.6.0
  vue: ^3.5.18